export const REQUEST_ALL_PRODUCTS_SUCCESS ='REQUEST_ALL_PRODUCTS_SUCCESS'; 

// Category List

export const REQUEST_CATEGORY_LIST_SUCCESS ='REQUEST_CATEGORY_LIST_SUCCESS'; 

// product detail

export const REQUEST_PRODUCT_DETAIL_SUCCESS = 'REQUEST_PRODUCT_DETAIL_SUCCESS';

// Cart List 

export const REQUEST_CART_LIST_SUCCESS = 'REQUEST_CART_LIST_SUCCESS';